[phases.setup]
nixPkgs = ['python311', 'pip', 'gcc', 'ffmpeg', 'libsndfile']
nixLibs = ['glibc', 'gcc-unwrapped']

[phases.install]
cmds = [
    'pip install --no-cache-dir -r requirements.txt'
]

[phases.build]
cmds = [
    'echo "Build completed"'
]

[start]
cmd = 'cd backend && python app_production.py'

[variables]
PYTHONUNBUFFERED = "1"
FLASK_ENV = "production"